model_list:
# - model_name: gpt-4
#   litellm_params:
#     model: openai/gpt-4o
#     api_key: "os.environ/OPENAI_API_KEY"

# - model_name: claude
#   litellm_params:
#     model: anthropic/claude-3-5-sonnet-20240620
#     api_key: "os.environ/ANTHROPIC_API_KEY"

- model_name: llama
  litellm_params:
    model: github/Llama-4-Scout-17B-16E-Instruct
    api_key: "os.environ/GITHUB_TOKEN"
    api_base: "https://models.inference.ai.azure.com"

- model_name: ms-phi
  litellm_params:
    model: github/Phi-4-reasoning
    api_key: "os.environ/GITHUB_TOKEN"
    api_base: "https://models.inference.ai.azure.com"

- model_name: ministral-3b
  litellm_params:
    model: github/Ministral-3B
    api_key: "os.environ/GITHUB_TOKEN"
    api_base: "https://models.inference.ai.azure.com"

- model_name: gemini
  litellm_params:
    model: huggingface/google/gemma-2-27b-it # Example gemma/gemini via HF
    api_key: "os.environ/HUGGINGFACE_API_KEY"
    api_base: "https://api-inference.huggingface.co/models/google/gemma-2-27b-it"
