"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    ...
def get_hook_lineage_collector(): # -> HookLineageCollector:
    """
    Return a hook lineage collector with all required compatibility layers applied.

    Compatibility is determined by inspecting the collector's available methods and
    properties (duck typing), rather than relying on the Airflow version number.

    Behavior by example:
    Airflow 2: Collector is missing asset-based methods and `add_extra` - apply both layers.
    Airflow 3.0–3.1: Collector has asset-based methods but lacks `add_extra` - apply single layer.
    Airflow 3.2+: Collector has asset-based methods and `add_extra` support - no action required.
    """
    ...

