"""
This type stub file was generated by pyright.
"""

"""
Reusable utilities for creating compatibility layers with fallback imports.

This module provides the core machinery used by sdk.py and standard/* modules
to handle import fallbacks between Airflow 3.x and 2.x.
"""
def create_module_getattr(import_map: dict[str, str | tuple[str, ...]], module_map: dict[str, str | tuple[str, ...]] | None = ..., rename_map: dict[str, tuple[str, str, str]] | None = ...): # -> Callable[..., Any | ModuleType]:
    """
    Create a __getattr__ function for lazy imports with fallback support.

    :param import_map: Dictionary mapping attribute names to module paths (single or tuple for fallback)
    :param module_map: Dictionary mapping module names to module paths (single or tuple for fallback)
    :param rename_map: Dictionary mapping new names to (new_path, old_path, old_name) tuples
    :return: A __getattr__ function that can be assigned at module level
    """
    ...

