"""
This type stub file was generated by pyright.
"""

import functools

@functools.cache
def get_base_airflow_version_tuple() -> tuple[int, int, int]:
    ...

AIRFLOW_V_3_0_PLUS = ...
AIRFLOW_V_3_1_PLUS: bool = ...
AIRFLOW_V_3_1_1_PLUS: bool = ...
__all__ = ["AIRFLOW_V_3_0_PLUS", "AIRFLOW_V_3_1_PLUS", "AIRFLOW_V_3_1_1_PLUS", "NOTSET", "ArgNotSet", "is_arg_set"]
